### ISSUE TITLE
throw xmlParseEntityRef when rendering medium API articles.

### ISSUE THREAD

**Issue by Fliw** [omidnikrah/github-readme-medium#4]
Hi There! i'm trying to use this tools, it was a great tools and i'm excited about it, then i'm start to implement it but it throw an error like this 
![image](https://user-images.githubusercontent.com/56640907/126758344-90815f75-b5b6-4616-9fa1-3657f2842f72.png)
On Link : https://github-readme-medium.vercel.app/?username=muhammadraflyindrawan
Thanks!

**Comment by omidnikrah** [comment]
Hi @Fliw 
Thank you for letting me know.
Now it's fixed and you can use it :)

**Comment by Fliw** [comment]
> Hi @Fliw 
> Thank you for letting me know.
> Now it's fixed and you can use it :)

Nice, thanks man!
